# Generated by Django 5.0.2 on 2024-05-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_comics_characters_comics_characters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comics',
            old_name='characters',
            new_name='character',
        ),
    ]
