# Generated by Django 5.0.2 on 2024-05-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_characters_comics_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comics',
            old_name='character',
            new_name='characters',
        ),
    ]
